# Generated by Django 5.0 on 2024-01-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='weigth',
            new_name='weight',
        ),
    ]
